### ISSUE TITLE
[Feature] Admin Page Frontend

### ISSUE THREAD

**Issue by FegelSamuel** [UTDallasEPICS/UTDesign-Monitor-Dashboard#1]
**Feature Description**
This is an Admin-Only Page (does not need to be admin-only right now, since we don't have a database to store user roles yet).

**Requirements**
- These are just buttons
 - allow admin to view all current users
 - allow admin to add new user
 - allow admin to add other admins
 - allow admin to remove users
 - allow admin to remove shared dashboards

**Additional context**
No backend functionality required for now.

**Comment by madeline-dotcom** [comment]
added the buttons
