### ISSUE TITLE
[Feature] Make Slides only able to display only one kind of URL at a time.

### ISSUE THREAD

**Issue by madeline-dotcom** [UTDallasEPICS/UTDesign-Monitor-Dashboard#66]
**Feature Description**
So we want to have only a specific kind of media be displayed in a given slide. One slide should not be presenting multiple kinds of media, that doesn't work. 

**Requirements**
The user chooses the type of Slide the given slide is with a drop-down or something (or a list that has a singular checkmark). After confirming, the client will send a PUT request to the database to update the given slide's type with `image`, `video`, xor `website`. We won't walk into the issue of having the `image`, `video`, and `website` URLs conflicting.

**Additional context**
Let Samuel or Allison know you don't know how to work on this! You will need to update the Prisma Schema and then run these commands:

(this resets your database)
```bash
npx prisma migrate reset
npx prisma migrate dev
```
If these don't work, you probably have to generate a Prisma Client with:
```bash
npx prisma generate
```

**Comment by FegelSamuel** [comment]
Prisma schema has not been modified, it needs to also be modified
