### ISSUE TITLE
[Feature] Owned Dashboards Toggle

### ISSUE THREAD

**Issue by FegelSamuel** [UTDallasEPICS/UTDesign-Monitor-Dashboard#73]
**Feature Description**
In the Dashboard List, we want a toggle button to see either only Dashboards you own or all Dashboards

**Requirements**
When it's clicked, it will switch from "only seeing your own dashboards" to "seeing all dashboards."
I would like you to, "on click," change the colors when toggling

**Additional context**
You will probably use the @click function.

**Comment by FegelSamuel** [comment]
Use a v-if and a ref probably

**Comment by madeline-dotcom** [comment]
done
