### ISSUE TITLE
Toolcrib application using auth0: add users

### ISSUE THREAD

**Issue by juhisahay** [UTDallasEPICS/UTDesign-Monitor-Dashboard#8]
Toolcrib Application:
- Passes user roles
https://github.com/UTDallasEPICS/UTDesign-Tool-Crib/blob/main/README.md

**Requirements**
A clear and concise list of what functionality will be needed

**Additional context**
Add any other context or screenshots about the feature here.

**Comment by FegelSamuel** [comment]
If this is not done by the time Juhi and I finish the APIs, I will start working on this with you, Harsh. 👍

**Comment by harshptl05** [comment]
# auth.ts
Inside of `auth.ts` (filepath is: `/UTDesign-Monitor-Dashboard-2/server/api/auth0.ts` ), this code is going to be used:

```ts
import {nanoid} from "nanoid"

const state = {}; 
const genState = () => { const s = nanoid(); state[s] = 1;  return s}
const runtime = useRuntimeConfig()

export const loginRedirectUrl = () => `${runtime.ISSUER}authorize?response_type=id_token&response_mode=form_post&client_id=${runtime.AUTH0_CLIENTID}&scope=openid%20email&redirect_uri=${encodeURIComponent(runtime.BASEURL!+"api/callback")}&nonce=${genState()}`
export const logoutRedirectUrl = (id_token: string) => `${runtime.ISSUER}oidc/logout?id_token_hint=${id_token}&post_logout_redirect_uri=${encodeURIComponent(runtime.BASEURL!+"api/logout-complete")}&nonce=${genState()}`


export const verifyNonce = (nonce: string) => {
  if (state[nonce]) {
    delete state[nonce]
```
# login.get.ts
## Filepath
```powershell
/UTDesign-Monitor-Dashboard-2/server/api/server.get.ts
```
## Contents
```ts
import { loginRedirectUrl } from "./auth0"

export default defineEventHandler(async event => {
  await sendRedirect(event, loginRedirectUrl() || "")
})
```
## Explanation
This is just redirecting you to the login page. It's called in the auth.ts file in `middleware` directory (a sibling directory of `api` inside of `server`, looking like `server/middleware/auth.ts`

**Comment by harshptl05** [comment]
# Reference Code
https://github.com/UTDallasEPICS/Carson-s-Village/blob/stage/server/middleware/auth.ts
Everything regarding Stripe is meaningless for us, don't copy it.
